export interface BibleVerse {
  reference: string;
  book: string;
  chapter: number;
  verse: number;
  verseEnd?: number;
  text: string;
  topics: string[];
}

export const BIBLE_VERSES: BibleVerse[] = [
  // Genesis
  {
    reference: "Genesis 1:1",
    book: "Genesis",
    chapter: 1,
    verse: 1,
    text: "In the beginning God created the heaven and the earth.",
    topics: ["creation", "God", "beginning"],
  },
  {
    reference: "Genesis 1:27",
    book: "Genesis",
    chapter: 1,
    verse: 27,
    text: "So God created man in his own image, in the image of God created he him; male and female created he them.",
    topics: ["creation", "humanity", "image of God"],
  },
  {
    reference: "Genesis 3:15",
    book: "Genesis",
    chapter: 3,
    verse: 15,
    text: "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel.",
    topics: ["prophecy", "messiah", "redemption"],
  },
  {
    reference: "Genesis 12:2",
    book: "Genesis",
    chapter: 12,
    verse: 2,
    text: "And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing.",
    topics: ["Abraham", "covenant", "blessing"],
  },
  // Exodus
  {
    reference: "Exodus 3:14",
    book: "Exodus",
    chapter: 3,
    verse: 14,
    text: "And God said unto Moses, I AM THAT I AM: and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you.",
    topics: ["God", "name of God", "Moses"],
  },
  {
    reference: "Exodus 20:3",
    book: "Exodus",
    chapter: 20,
    verse: 3,
    text: "Thou shalt have no other gods before me.",
    topics: ["commandments", "worship", "idolatry"],
  },
  // Deuteronomy
  {
    reference: "Deuteronomy 6:4-5",
    book: "Deuteronomy",
    chapter: 6,
    verse: 4,
    verseEnd: 5,
    text: "Hear, O Israel: The LORD our God is one LORD: And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.",
    topics: ["love", "God", "Shema", "commandments"],
  },
  {
    reference: "Deuteronomy 31:6",
    book: "Deuteronomy",
    chapter: 31,
    verse: 6,
    text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
    topics: ["courage", "strength", "faithfulness"],
  },
  // Joshua
  {
    reference: "Joshua 1:9",
    book: "Joshua",
    chapter: 1,
    verse: 9,
    text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    topics: ["courage", "strength", "God's presence"],
  },
  // Psalms
  {
    reference: "Psalm 23:1",
    book: "Psalms",
    chapter: 23,
    verse: 1,
    text: "The LORD is my shepherd; I shall not want.",
    topics: ["trust", "provision", "shepherd"],
  },
  {
    reference: "Psalm 23:4",
    book: "Psalms",
    chapter: 23,
    verse: 4,
    text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    topics: ["comfort", "death", "God's presence", "fear"],
  },
  {
    reference: "Psalm 27:1",
    book: "Psalms",
    chapter: 27,
    verse: 1,
    text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    topics: ["light", "salvation", "fear", "strength"],
  },
  {
    reference: "Psalm 34:18",
    book: "Psalms",
    chapter: 34,
    verse: 18,
    text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.",
    topics: ["brokenness", "comfort", "salvation"],
  },
  {
    reference: "Psalm 46:1",
    book: "Psalms",
    chapter: 46,
    verse: 1,
    text: "God is our refuge and strength, a very present help in trouble.",
    topics: ["refuge", "strength", "help", "trouble"],
  },
  {
    reference: "Psalm 51:10",
    book: "Psalms",
    chapter: 51,
    verse: 10,
    text: "Create in me a clean heart, O God; and renew a right spirit within me.",
    topics: ["repentance", "renewal", "heart", "purity"],
  },
  {
    reference: "Psalm 91:1-2",
    book: "Psalms",
    chapter: 91,
    verse: 1,
    verseEnd: 2,
    text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.",
    topics: ["protection", "trust", "refuge"],
  },
  {
    reference: "Psalm 119:105",
    book: "Psalms",
    chapter: 119,
    verse: 105,
    text: "Thy word is a lamp unto my feet, and a light unto my path.",
    topics: ["Bible", "guidance", "light", "word of God"],
  },
  {
    reference: "Psalm 139:14",
    book: "Psalms",
    chapter: 139,
    verse: 14,
    text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.",
    topics: ["creation", "praise", "self-worth", "identity"],
  },
  // Proverbs
  {
    reference: "Proverbs 3:5-6",
    book: "Proverbs",
    chapter: 3,
    verse: 5,
    verseEnd: 6,
    text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    topics: ["trust", "guidance", "wisdom"],
  },
  {
    reference: "Proverbs 22:6",
    book: "Proverbs",
    chapter: 22,
    verse: 6,
    text: "Train up a child in the way he should go: and when he is old, he will not depart from it.",
    topics: ["children", "parenting", "training", "wisdom"],
  },
  {
    reference: "Proverbs 27:17",
    book: "Proverbs",
    chapter: 27,
    verse: 17,
    text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
    topics: ["friendship", "community", "growth"],
  },
  // Ecclesiastes
  {
    reference: "Ecclesiastes 3:1",
    book: "Ecclesiastes",
    chapter: 3,
    verse: 1,
    text: "To every thing there is a season, and a time to every purpose under the heaven.",
    topics: ["time", "seasons", "purpose", "wisdom"],
  },
  // Isaiah
  {
    reference: "Isaiah 9:6",
    book: "Isaiah",
    chapter: 9,
    verse: 6,
    text: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.",
    topics: ["prophecy", "messiah", "Jesus", "Christmas"],
  },
  {
    reference: "Isaiah 40:31",
    book: "Isaiah",
    chapter: 40,
    verse: 31,
    text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    topics: ["strength", "patience", "renewal", "hope"],
  },
  {
    reference: "Isaiah 41:10",
    book: "Isaiah",
    chapter: 41,
    verse: 10,
    text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    topics: ["fear", "strength", "God's presence", "comfort"],
  },
  {
    reference: "Isaiah 53:5",
    book: "Isaiah",
    chapter: 53,
    verse: 5,
    text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
    topics: ["prophecy", "messiah", "suffering", "healing", "atonement"],
  },
  // Jeremiah
  {
    reference: "Jeremiah 29:11",
    book: "Jeremiah",
    chapter: 29,
    verse: 11,
    text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
    topics: ["hope", "future", "plans", "God's will"],
  },
  {
    reference: "Jeremiah 33:3",
    book: "Jeremiah",
    chapter: 33,
    verse: 3,
    text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.",
    topics: ["prayer", "revelation", "God's response"],
  },
  // Lamentations
  {
    reference: "Lamentations 3:22-23",
    book: "Lamentations",
    chapter: 3,
    verse: 22,
    verseEnd: 23,
    text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
    topics: ["mercy", "faithfulness", "compassion", "morning"],
  },
  // Micah
  {
    reference: "Micah 6:8",
    book: "Micah",
    chapter: 6,
    verse: 8,
    text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
    topics: ["justice", "mercy", "humility", "righteousness"],
  },
  // Matthew
  {
    reference: "Matthew 5:14",
    book: "Matthew",
    chapter: 5,
    verse: 14,
    text: "Ye are the light of the world. A city that is set on an hill cannot be hid.",
    topics: ["light", "witness", "sermon on the mount"],
  },
  {
    reference: "Matthew 5:44",
    book: "Matthew",
    chapter: 5,
    verse: 44,
    text: "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you.",
    topics: ["love", "enemies", "forgiveness", "sermon on the mount"],
  },
  {
    reference: "Matthew 6:33",
    book: "Matthew",
    chapter: 6,
    verse: 33,
    text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    topics: ["kingdom", "priorities", "provision", "righteousness"],
  },
  {
    reference: "Matthew 7:7",
    book: "Matthew",
    chapter: 7,
    verse: 7,
    text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.",
    topics: ["prayer", "seeking", "persistence"],
  },
  {
    reference: "Matthew 11:28",
    book: "Matthew",
    chapter: 11,
    verse: 28,
    text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
    topics: ["rest", "comfort", "Jesus", "invitation"],
  },
  {
    reference: "Matthew 22:37-39",
    book: "Matthew",
    chapter: 22,
    verse: 37,
    verseEnd: 39,
    text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself.",
    topics: ["love", "commandments", "greatest commandment"],
  },
  {
    reference: "Matthew 28:19-20",
    book: "Matthew",
    chapter: 28,
    verse: 19,
    verseEnd: 20,
    text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you always, even unto the end of the world.",
    topics: ["great commission", "evangelism", "baptism", "Trinity"],
  },
  // Mark
  {
    reference: "Mark 10:27",
    book: "Mark",
    chapter: 10,
    verse: 27,
    text: "And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible.",
    topics: ["faith", "impossible", "God's power"],
  },
  {
    reference: "Mark 12:30-31",
    book: "Mark",
    chapter: 12,
    verse: 30,
    verseEnd: 31,
    text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment. And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these.",
    topics: ["love", "commandments"],
  },
  // Luke
  {
    reference: "Luke 1:37",
    book: "Luke",
    chapter: 1,
    verse: 37,
    text: "For with God nothing shall be impossible.",
    topics: ["faith", "God's power", "possibility"],
  },
  {
    reference: "Luke 6:31",
    book: "Luke",
    chapter: 6,
    verse: 31,
    text: "And as ye would that men should do to you, do ye also to them likewise.",
    topics: ["golden rule", "love", "ethics"],
  },
  {
    reference: "Luke 23:34",
    book: "Luke",
    chapter: 23,
    verse: 34,
    text: "Then said Jesus, Father, forgive them; for they know not what they do.",
    topics: ["forgiveness", "crucifixion", "Jesus"],
  },
  // John
  {
    reference: "John 1:1",
    book: "John",
    chapter: 1,
    verse: 1,
    text: "In the beginning was the Word, and the Word was with God, and the Word was God.",
    topics: ["Jesus", "divinity", "Word", "creation"],
  },
  {
    reference: "John 1:14",
    book: "John",
    chapter: 1,
    verse: 14,
    text: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.",
    topics: ["incarnation", "Jesus", "grace", "truth"],
  },
  {
    reference: "John 3:16",
    book: "John",
    chapter: 3,
    verse: 16,
    text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    topics: ["love", "salvation", "eternal life", "faith"],
  },
  {
    reference: "John 3:17",
    book: "John",
    chapter: 3,
    verse: 17,
    text: "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
    topics: ["salvation", "grace", "judgment"],
  },
  {
    reference: "John 8:32",
    book: "John",
    chapter: 8,
    verse: 32,
    text: "And ye shall know the truth, and the truth shall make you free.",
    topics: ["truth", "freedom", "knowledge"],
  },
  {
    reference: "John 10:10",
    book: "John",
    chapter: 10,
    verse: 10,
    text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.",
    topics: ["abundant life", "Jesus", "purpose"],
  },
  {
    reference: "John 11:25-26",
    book: "John",
    chapter: 11,
    verse: 25,
    verseEnd: 26,
    text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die.",
    topics: ["resurrection", "eternal life", "faith", "Jesus"],
  },
  {
    reference: "John 13:34-35",
    book: "John",
    chapter: 13,
    verse: 34,
    verseEnd: 35,
    text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another.",
    topics: ["love", "discipleship", "commandments"],
  },
  {
    reference: "John 14:6",
    book: "John",
    chapter: 14,
    verse: 6,
    text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
    topics: ["Jesus", "salvation", "truth", "way"],
  },
  {
    reference: "John 14:27",
    book: "John",
    chapter: 14,
    verse: 27,
    text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
    topics: ["peace", "comfort", "Jesus"],
  },
  {
    reference: "John 15:13",
    book: "John",
    chapter: 15,
    verse: 13,
    text: "Greater love hath no man than this, that a man lay down his life for his friends.",
    topics: ["love", "sacrifice", "friendship"],
  },
  {
    reference: "John 16:33",
    book: "John",
    chapter: 16,
    verse: 33,
    text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
    topics: ["peace", "tribulation", "overcoming", "Jesus"],
  },
  // Acts
  {
    reference: "Acts 1:8",
    book: "Acts",
    chapter: 1,
    verse: 8,
    text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.",
    topics: ["Holy Spirit", "witness", "power", "evangelism"],
  },
  {
    reference: "Acts 2:38",
    book: "Acts",
    chapter: 2,
    verse: 38,
    text: "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.",
    topics: ["repentance", "baptism", "Holy Spirit", "salvation"],
  },
  // Romans
  {
    reference: "Romans 3:23",
    book: "Romans",
    chapter: 3,
    verse: 23,
    text: "For all have sinned, and come short of the glory of God.",
    topics: ["sin", "humanity", "glory of God"],
  },
  {
    reference: "Romans 5:8",
    book: "Romans",
    chapter: 5,
    verse: 8,
    text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
    topics: ["love", "grace", "atonement", "salvation"],
  },
  {
    reference: "Romans 6:23",
    book: "Romans",
    chapter: 6,
    verse: 23,
    text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.",
    topics: ["sin", "death", "eternal life", "gift", "salvation"],
  },
  {
    reference: "Romans 8:1",
    book: "Romans",
    chapter: 8,
    verse: 1,
    text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
    topics: ["freedom", "condemnation", "grace", "Spirit"],
  },
  {
    reference: "Romans 8:28",
    book: "Romans",
    chapter: 8,
    verse: 28,
    text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    topics: ["purpose", "good", "God's plan", "hope"],
  },
  {
    reference: "Romans 8:38-39",
    book: "Romans",
    chapter: 8,
    verse: 38,
    verseEnd: 39,
    text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.",
    topics: ["love", "security", "eternal", "God's love"],
  },
  {
    reference: "Romans 10:9",
    book: "Romans",
    chapter: 10,
    verse: 9,
    text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
    topics: ["salvation", "faith", "confession", "resurrection"],
  },
  {
    reference: "Romans 12:2",
    book: "Romans",
    chapter: 12,
    verse: 2,
    text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
    topics: ["transformation", "mind", "God's will", "renewal"],
  },
  // 1 Corinthians
  {
    reference: "1 Corinthians 10:13",
    book: "1 Corinthians",
    chapter: 10,
    verse: 13,
    text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.",
    topics: ["temptation", "faithfulness", "endurance"],
  },
  {
    reference: "1 Corinthians 13:4-7",
    book: "1 Corinthians",
    chapter: 13,
    verse: 4,
    verseEnd: 7,
    text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things.",
    topics: ["love", "charity", "patience", "kindness"],
  },
  {
    reference: "1 Corinthians 13:13",
    book: "1 Corinthians",
    chapter: 13,
    verse: 13,
    text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    topics: ["love", "faith", "hope"],
  },
  {
    reference: "1 Corinthians 15:55-57",
    book: "1 Corinthians",
    chapter: 15,
    verse: 55,
    verseEnd: 57,
    text: "O death, where is thy sting? O grave, where is thy victory? The sting of death is sin; and the strength of sin is the law. But thanks be to God, which giveth us the victory through our Lord Jesus Christ.",
    topics: ["death", "victory", "resurrection"],
  },
  // 2 Corinthians
  {
    reference: "2 Corinthians 5:17",
    book: "2 Corinthians",
    chapter: 5,
    verse: 17,
    text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    topics: ["new creation", "transformation", "Christ"],
  },
  {
    reference: "2 Corinthians 12:9",
    book: "2 Corinthians",
    chapter: 12,
    verse: 9,
    text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.",
    topics: ["grace", "weakness", "strength", "sufficiency"],
  },
  // Galatians
  {
    reference: "Galatians 2:20",
    book: "Galatians",
    chapter: 2,
    verse: 20,
    text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.",
    topics: ["faith", "Christ", "crucifixion", "identity"],
  },
  {
    reference: "Galatians 5:22-23",
    book: "Galatians",
    chapter: 5,
    verse: 22,
    verseEnd: 23,
    text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.",
    topics: ["fruit of the Spirit", "Holy Spirit", "character"],
  },
  // Ephesians
  {
    reference: "Ephesians 2:8-9",
    book: "Ephesians",
    chapter: 2,
    verse: 8,
    verseEnd: 9,
    text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.",
    topics: ["grace", "faith", "salvation", "works"],
  },
  {
    reference: "Ephesians 4:32",
    book: "Ephesians",
    chapter: 4,
    verse: 32,
    text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    topics: ["kindness", "forgiveness", "compassion"],
  },
  {
    reference: "Ephesians 6:11",
    book: "Ephesians",
    chapter: 6,
    verse: 11,
    text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
    topics: ["armor of God", "spiritual warfare", "protection"],
  },
  // Philippians
  {
    reference: "Philippians 1:6",
    book: "Philippians",
    chapter: 1,
    verse: 6,
    text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.",
    topics: ["confidence", "God's work", "perseverance"],
  },
  {
    reference: "Philippians 2:3-4",
    book: "Philippians",
    chapter: 2,
    verse: 3,
    verseEnd: 4,
    text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves. Look not every man on his own things, but every man also on the things of others.",
    topics: ["humility", "selflessness", "others"],
  },
  {
    reference: "Philippians 4:6-7",
    book: "Philippians",
    chapter: 4,
    verse: 6,
    verseEnd: 7,
    text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    topics: ["anxiety", "prayer", "peace", "thanksgiving"],
  },
  {
    reference: "Philippians 4:13",
    book: "Philippians",
    chapter: 4,
    verse: 13,
    text: "I can do all things through Christ which strengtheneth me.",
    topics: ["strength", "Christ", "ability"],
  },
  // Colossians
  {
    reference: "Colossians 3:23",
    book: "Colossians",
    chapter: 3,
    verse: 23,
    text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
    topics: ["work", "service", "dedication"],
  },
  // 1 Thessalonians
  {
    reference: "1 Thessalonians 5:16-18",
    book: "1 Thessalonians",
    chapter: 5,
    verse: 16,
    verseEnd: 18,
    text: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
    topics: ["joy", "prayer", "thanksgiving", "God's will"],
  },
  // 2 Timothy
  {
    reference: "2 Timothy 1:7",
    book: "2 Timothy",
    chapter: 1,
    verse: 7,
    text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
    topics: ["fear", "power", "love", "courage"],
  },
  {
    reference: "2 Timothy 3:16",
    book: "2 Timothy",
    chapter: 3,
    verse: 16,
    text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.",
    topics: ["Bible", "scripture", "inspiration", "doctrine"],
  },
  // Hebrews
  {
    reference: "Hebrews 4:12",
    book: "Hebrews",
    chapter: 4,
    verse: 12,
    text: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.",
    topics: ["word of God", "Bible", "power"],
  },
  {
    reference: "Hebrews 11:1",
    book: "Hebrews",
    chapter: 11,
    verse: 1,
    text: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    topics: ["faith", "hope", "belief"],
  },
  {
    reference: "Hebrews 11:6",
    book: "Hebrews",
    chapter: 11,
    verse: 6,
    text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
    topics: ["faith", "seeking God", "reward"],
  },
  {
    reference: "Hebrews 12:1-2",
    book: "Hebrews",
    chapter: 12,
    verse: 1,
    verseEnd: 2,
    text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith.",
    topics: ["perseverance", "faith", "Jesus", "endurance"],
  },
  {
    reference: "Hebrews 13:8",
    book: "Hebrews",
    chapter: 13,
    verse: 8,
    text: "Jesus Christ the same yesterday, and to day, and for ever.",
    topics: ["Jesus", "unchanging", "eternal"],
  },
  // James
  {
    reference: "James 1:2-3",
    book: "James",
    chapter: 1,
    verse: 2,
    verseEnd: 3,
    text: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.",
    topics: ["trials", "joy", "patience", "faith"],
  },
  {
    reference: "James 1:5",
    book: "James",
    chapter: 1,
    verse: 5,
    text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
    topics: ["wisdom", "prayer", "asking"],
  },
  {
    reference: "James 4:7",
    book: "James",
    chapter: 4,
    verse: 7,
    text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
    topics: ["submission", "spiritual warfare", "devil"],
  },
  // 1 Peter
  {
    reference: "1 Peter 5:7",
    book: "1 Peter",
    chapter: 5,
    verse: 7,
    text: "Casting all your care upon him; for he careth for you.",
    topics: ["anxiety", "care", "trust", "God's love"],
  },
  // 1 John
  {
    reference: "1 John 1:9",
    book: "1 John",
    chapter: 1,
    verse: 9,
    text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
    topics: ["confession", "forgiveness", "cleansing", "faithfulness"],
  },
  {
    reference: "1 John 4:8",
    book: "1 John",
    chapter: 4,
    verse: 8,
    text: "He that loveth not knoweth not God; for God is love.",
    topics: ["love", "God", "nature of God"],
  },
  {
    reference: "1 John 4:19",
    book: "1 John",
    chapter: 4,
    verse: 19,
    text: "We love him, because he first loved us.",
    topics: ["love", "God's love", "initiative"],
  },
  // Revelation
  {
    reference: "Revelation 3:20",
    book: "Revelation",
    chapter: 3,
    verse: 20,
    text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me.",
    topics: ["invitation", "Jesus", "fellowship"],
  },
  {
    reference: "Revelation 21:4",
    book: "Revelation",
    chapter: 21,
    verse: 4,
    text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.",
    topics: ["heaven", "hope", "comfort", "eternal life", "new creation"],
  },
  {
    reference: "Revelation 22:13",
    book: "Revelation",
    chapter: 22,
    verse: 13,
    text: "I am Alpha and Omega, the beginning and the end, the first and the last.",
    topics: ["Jesus", "eternal", "divinity"],
  },
];

export const VALID_BOOKS = [
  "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
  "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
  "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles",
  "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Psalm",
  "Proverbs", "Ecclesiastes", "Song of Solomon",
  "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel",
  "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah",
  "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi",
  "Matthew", "Mark", "Luke", "John", "Acts",
  "Romans", "1 Corinthians", "2 Corinthians", "Galatians",
  "Ephesians", "Philippians", "Colossians",
  "1 Thessalonians", "2 Thessalonians",
  "1 Timothy", "2 Timothy", "Titus", "Philemon",
  "Hebrews", "James", "1 Peter", "2 Peter",
  "1 John", "2 John", "3 John", "Jude", "Revelation",
];

export const DEUTEROCANONICAL_BOOKS = [
  "Tobit", "Judith", "1 Maccabees", "2 Maccabees",
  "Wisdom", "Wisdom of Solomon", "Sirach", "Ecclesiasticus",
  "Baruch", "Letter of Jeremiah",
  "Additions to Esther", "Additions to Daniel",
  "Prayer of Azariah", "Susanna", "Bel and the Dragon",
];

export function findVerseByReference(reference: string): BibleVerse | undefined {
  const normalized = reference.trim().replace(/\s+/g, " ");
  return BIBLE_VERSES.find(
    (v) => v.reference.toLowerCase() === normalized.toLowerCase()
  );
}

export function findVersesByTopic(topic: string): BibleVerse[] {
  const lower = topic.toLowerCase();
  return BIBLE_VERSES.filter((v) =>
    v.topics.some((t) => t.toLowerCase().includes(lower))
  );
}

export function searchVerses(query: string): BibleVerse[] {
  const lower = query.toLowerCase();
  return BIBLE_VERSES.filter(
    (v) =>
      v.text.toLowerCase().includes(lower) ||
      v.reference.toLowerCase().includes(lower) ||
      v.topics.some((t) => t.toLowerCase().includes(lower))
  );
}
